### ISSUE TITLE
ENOENT: no such file or directory

### ISSUE THREAD

**Issue by allykr** [shogerr/bluprntr#13]
I'm getting this error after trying to install this morning: 

Error: ENOENT: no such file or directory, open '/Users/ally/Documents/bluprntr-master/node_modules/youtube-dl/bin/details'

**Comment by shogerr** [comment]
I've seen this one before...
Can you try removing the `node_modules/` folder itself, and then reinstalling? This may clean up the issue.

**Comment by shogerr** [comment]
Little bit of an update: @allykr could you try using Git instead of downloading the package? I remember last week a dependency that's used had issues. I hand rolled a solution to keep this project working, but it may rely upon Git to work. I'll see what I can do to clean this up.

**Comment by shogerr** [comment]
And it seem's they've cleaned up the problem they were having, so the latest update may work for you.

**Comment by allykr** [comment]
I ended up getting my classes though a different method so I removed the files from my computer. This one was a bit too technical for my skill level. But thank you!
