### ISSUE TITLE
Uncaught TypeError: Cannot read property 'query' of undefined

### ISSUE THREAD

**Issue by lisaanncassidy** [shogerr/bluprntr#3]
<img width="653" alt="Screenshot 2020-06-04 at 14 12 01" src="https://user-images.githubusercontent.com/3791297/83760921-861e4c00-a66d-11ea-8539-845ba55b7b20.png">
This absolutely might be user error, but the above is occurring every time I clear and attempt to start again

The designated download path contains nothing, and it isn't entirely clear to me what I should be seeing in the network tab following clicking the video.

Thank you for your development work, I'd love to get this running!

**Comment by shogerr** [comment]
I think today I will work on a new tab routine. The change will be to query all the tabs, and filter by the open url. I think I will make this method selectable by the user. That should be more robust, but a little slower.

**Comment by shogerr** [comment]
@lisaanncassidy I just added more permissions to the extension. They shouldn't be necessary with the version of Chrome that we're both using, but it can't hurt.

```javascript
{
  "manifest_version": 2,
  "name": "BluPrntr",
  "version": "0.1",
  "permissions": [
    "declarativeContent",
    "storage",
    "tabs",
    "<all_urls>",
    "activeTab",
    "http://*/*",
    "https://*/*"
  ],
```
Try using the updated code... it may help, but maybe not. The error you are encountering is not one I would expect. It happens, but only if the programmer is trying to query tabs from say, a content script, which isn't the case here.

Can you also try removing the extension completely, closing chrome, re-opening chrome and adding the extension back? I haven't been able to reproduce your problem specifically, so best to try to reload everything completely.

**Comment by lisaanncassidy** [comment]
This seems to have done the trick, thank you!
