### ISSUE TITLE
In Readme, it's unclear in which folder things happen

### ISSUE THREAD

**Issue by danielaKay** [shogerr/bluprntr#5]
Hello shogerr

I just provided tech support for a friend who wanted to use your tool. 
Her problem was that she ran "npm install" in the wrong folder.

Maybe it would be helpful to mention in the Readme file that "npm install" and everything after that needs to be run in the same folder that contains the package.json? 

Best regards,
DanielaKay

**Comment by shogerr** [comment]
Thanks @danielaKay, I'll make your suggested change to the README. You're spot on with that recommendation.
