### ISSUE TITLE
Video download

### ISSUE THREAD

**Issue by liloxk** [shogerr/bluprntr#8]
I have installed the server and and the program. 
The resources files download correctly, but the videos don't. Powershell gives me that error ; 'ERROR: m3u8 download detected but ffmpeg or avconv could not be found. Please install one.' 
[https://ibb.co/cv3pbS1](url)

Thank you for your help !

**Comment by shogerr** [comment]
Thanks for reporting the problem! It was not documented that a system _must_ have the ffmpeg tools installed. I've updated the README. For anyone else having problems, install ffmpeg and make sure it's  tools are in your path.

**Comment by shogerr** [comment]
Re-opening to include a fix that uses an npm package instead of a system's

**Comment by shogerr** [comment]
Re-opening to include a fix that uses an npm package instead of a system's
