### ISSUE TITLE
Extension not connecting to local server

### ISSUE THREAD

**Issue by devshorts** [shogerr/bluprntr#9]
Howdy, trying to get this to run and I can't seem to get the extension to connect to the local server at all. If I enable the devtools panel as a background page I can see that it connects, but doesn't attach to the network request listener to the get the m3u master playlist.

Are there any suggestions on how to debug this or get more information about why it isn't connecting? Is it permissions? I can't seem to get any logging if I don't have it enabled as a background page. 

Thanks!

**Comment by shogerr** [comment]
I just pushed a new update, so hopefully that won't confuse things. There are some options for the extension to change the port, you may try those. There is also a small test server that can be started with `yarn test-server`. This will _just_ show you what's coming through the socket.

I'll add a little more to the tests as well soon. For now, try the install method maybe, and get the new code -- not that I think that's the problem.

**Comment by shogerr** [comment]
Oh, also, closing and then re-opening Chrome's **Developer Tools** _without_ refreshing is all it takes to reconnect to the listening socket I've found out. So I will hit 'f12' twice to when I'm testing to reload.
